name: Deploy TruePortMe Frontend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Build inside GitHub runner (fast)
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # Upload only build artifacts to EC2 (no node_modules)
      - name: Upload built files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".next,out,public,package.json,package-lock.json"
          target: "/var/www/trueportme-frontend"

      # Create env + restart PM2 (no rebuild here)
      - name: Create .env.production and restart frontend
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/trueportme-frontend
            echo "${{ secrets.PROD_ENV_FILE }}" > .env.production
            pm2 restart trueportme-frontend --update-env || pm2 start npm --name trueportme-frontend --cwd /var/www/trueportme-frontend -- start
